<!DOCTYPE html>
<html lang="en-US">
<!--********************************************-->
<!--*       Generated from PreTeXt source      *-->
<!--*                                          *-->
<!--*         https://pretextbook.org          *-->
<!--*                                          *-->
<!--********************************************-->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="robots" content="noindex, nofollow">
</head>
<body class="ignore-math">
<h5 class="heading"><span class="type">Paragraph</span></h5>
<div class="para">Any exception generated in the indented block following a <code class="code-inline tex2jax_ignore">try:</code> command will attempt to be caught by one of a sequence of <code class="code-inline tex2jax_ignore">except ... :</code> blocks which follow. As only one exception is generated at a time, this behaves as an <code class="code-inline tex2jax_ignore">if:... elif:...</code> sequence; for instance, if one of the blocks begins with <code class="code-inline tex2jax_ignore">except RuntimeError as error_message:</code>, then that block will only be executed when the body of the <code class="code-inline tex2jax_ignore">try:</code> block raises a <code class="code-inline tex2jax_ignore">RuntimeError(...)</code>; the optional argument to the error is named <code class="code-inline tex2jax_ignore">error_message</code> within this <code class="code-inline tex2jax_ignore">except</code> block.</div>
<span class="incontext"><a href="sec-intro-errors.html#p-1014" class="internal">in-context</a></span>
</body>
</html>
